// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ks.code.type.domain;

import java.lang.String;

privileged aspect AgentType_Roo_JavaBean {
    
    public String AgentType.getName() {
        return this.name;
    }
    
    public void AgentType.setName(String name) {
        this.name = name;
    }
    
    public String AgentType.getCode() {
        return this.code;
    }
    
    public void AgentType.setCode(String code) {
        this.code = code;
    }
    
}
