// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ks.code.type.domain;

import com.ks.code.type.domain.AgentType;
import java.lang.Integer;
import java.lang.Long;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.PersistenceContext;
import javax.persistence.Table;
import javax.persistence.Version;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AgentType_Roo_Entity {
    
    declare @type: AgentType: @Entity;
    
    declare @type: AgentType: @Table(name = "ks_agent_type");
    
    @PersistenceContext
    transient EntityManager AgentType.entityManager;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long AgentType.id;
    
    @Version
    @Column(name = "version")
    private Integer AgentType.version;
    
    public Long AgentType.getId() {
        return this.id;
    }
    
    public void AgentType.setId(Long id) {
        this.id = id;
    }
    
    public Integer AgentType.getVersion() {
        return this.version;
    }
    
    public void AgentType.setVersion(Integer version) {
        this.version = version;
    }
    
    @Transactional
    public void AgentType.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void AgentType.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            AgentType attached = AgentType.findAgentType(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void AgentType.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void AgentType.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public AgentType AgentType.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        AgentType merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
    public static final EntityManager AgentType.entityManager() {
        EntityManager em = new AgentType().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long AgentType.countAgentTypes() {
        return entityManager().createQuery("SELECT COUNT(o) FROM AgentType o", Long.class).getSingleResult();
    }
    
    public static List<AgentType> AgentType.findAllAgentTypes() {
        return entityManager().createQuery("SELECT o FROM AgentType o", AgentType.class).getResultList();
    }
    
    public static AgentType AgentType.findAgentType(Long id) {
        if (id == null) return null;
        return entityManager().find(AgentType.class, id);
    }
    
    public static List<AgentType> AgentType.findAgentTypeEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM AgentType o", AgentType.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
