// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ks.code.calculator.service;

import com.ks.code.calculator.domain.WeekAgentLog;
import java.lang.Long;
import java.lang.String;
import java.util.List;

privileged aspect WeekAgentLogServiceResult_Roo_JavaBean {
    
    public WeekAgentLog WeekAgentLogServiceResult.getWeekagentlog() {
        return this.weekagentlog;
    }
    
    public void WeekAgentLogServiceResult.setWeekagentlog(WeekAgentLog weekagentlog) {
        this.weekagentlog = weekagentlog;
    }
    
    public List<WeekAgentLog> WeekAgentLogServiceResult.getWeekagentlogList() {
        return this.weekagentlogList;
    }
    
    public void WeekAgentLogServiceResult.setWeekagentlogList(List<WeekAgentLog> weekagentlogList) {
        this.weekagentlogList = weekagentlogList;
    }
    
    public Long WeekAgentLogServiceResult.getCount() {
        return this.count;
    }
    
    public void WeekAgentLogServiceResult.setCount(Long count) {
        this.count = count;
    }
    
    public String WeekAgentLogServiceResult.getPageView() {
        return this.pageView;
    }
    
    public void WeekAgentLogServiceResult.setPageView(String pageView) {
        this.pageView = pageView;
    }
    
}
