// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ks.code.calculator.domain;

import java.lang.Long;
import java.lang.String;
import java.util.Date;

privileged aspect TimeAgentLog_Roo_JavaBean {
    
    public Long TimeAgentLog.getCodeCreatorId() {
        return this.codeCreatorId;
    }
    
    public void TimeAgentLog.setCodeCreatorId(Long codeCreatorId) {
        this.codeCreatorId = codeCreatorId;
    }
    
    public String TimeAgentLog.getAgent() {
        return this.agent;
    }
    
    public void TimeAgentLog.setAgent(String agent) {
        this.agent = agent;
    }
    
    public Long TimeAgentLog.getCount() {
        return this.count;
    }
    
    public void TimeAgentLog.setCount(Long count) {
        this.count = count;
    }
    
    public Long TimeAgentLog.getLogTime() {
        return this.logTime;
    }
    
    public void TimeAgentLog.setLogTime(Long logTime) {
        this.logTime = logTime;
    }
    
    public Date TimeAgentLog.getWriteDate() {
        return this.writeDate;
    }
    
    public void TimeAgentLog.setWriteDate(Date writeDate) {
        this.writeDate = writeDate;
    }
    
}
