// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ks.code.calculator.domain;

import com.ks.code.calculator.domain.TimeAgentLog;
import java.lang.Integer;
import java.lang.Long;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.PersistenceContext;
import javax.persistence.Table;
import javax.persistence.Version;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TimeAgentLog_Roo_Entity {
    
    declare @type: TimeAgentLog: @Entity;
    
    declare @type: TimeAgentLog: @Table(name = "ks_time_agent_log");
    
    @PersistenceContext
    transient EntityManager TimeAgentLog.entityManager;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long TimeAgentLog.id;
    
    @Version
    @Column(name = "version")
    private Integer TimeAgentLog.version;
    
    public Long TimeAgentLog.getId() {
        return this.id;
    }
    
    public void TimeAgentLog.setId(Long id) {
        this.id = id;
    }
    
    public Integer TimeAgentLog.getVersion() {
        return this.version;
    }
    
    public void TimeAgentLog.setVersion(Integer version) {
        this.version = version;
    }
    
    @Transactional
    public void TimeAgentLog.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void TimeAgentLog.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            TimeAgentLog attached = TimeAgentLog.findTimeAgentLog(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void TimeAgentLog.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void TimeAgentLog.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public TimeAgentLog TimeAgentLog.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        TimeAgentLog merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
    public static final EntityManager TimeAgentLog.entityManager() {
        EntityManager em = new TimeAgentLog().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long TimeAgentLog.countTimeAgentLogs() {
        return entityManager().createQuery("SELECT COUNT(o) FROM TimeAgentLog o", Long.class).getSingleResult();
    }
    
    public static List<TimeAgentLog> TimeAgentLog.findAllTimeAgentLogs() {
        return entityManager().createQuery("SELECT o FROM TimeAgentLog o", TimeAgentLog.class).getResultList();
    }
    
    public static TimeAgentLog TimeAgentLog.findTimeAgentLog(Long id) {
        if (id == null) return null;
        return entityManager().find(TimeAgentLog.class, id);
    }
    
    public static List<TimeAgentLog> TimeAgentLog.findTimeAgentLogEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM TimeAgentLog o", TimeAgentLog.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
