// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ks.code.calculator.domain;

import com.ks.code.calculator.domain.WeekAgentLog;
import java.lang.Integer;
import java.lang.Long;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.PersistenceContext;
import javax.persistence.Table;
import javax.persistence.Version;
import org.springframework.transaction.annotation.Transactional;

privileged aspect WeekAgentLog_Roo_Entity {
    
    declare @type: WeekAgentLog: @Entity;
    
    declare @type: WeekAgentLog: @Table(name = "ks_week_agent_log");
    
    @PersistenceContext
    transient EntityManager WeekAgentLog.entityManager;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long WeekAgentLog.id;
    
    @Version
    @Column(name = "version")
    private Integer WeekAgentLog.version;
    
    public Long WeekAgentLog.getId() {
        return this.id;
    }
    
    public void WeekAgentLog.setId(Long id) {
        this.id = id;
    }
    
    public Integer WeekAgentLog.getVersion() {
        return this.version;
    }
    
    public void WeekAgentLog.setVersion(Integer version) {
        this.version = version;
    }
    
    @Transactional
    public void WeekAgentLog.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void WeekAgentLog.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            WeekAgentLog attached = WeekAgentLog.findWeekAgentLog(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void WeekAgentLog.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void WeekAgentLog.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public WeekAgentLog WeekAgentLog.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        WeekAgentLog merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
    public static final EntityManager WeekAgentLog.entityManager() {
        EntityManager em = new WeekAgentLog().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long WeekAgentLog.countWeekAgentLogs() {
        return entityManager().createQuery("SELECT COUNT(o) FROM WeekAgentLog o", Long.class).getSingleResult();
    }
    
    public static List<WeekAgentLog> WeekAgentLog.findAllWeekAgentLogs() {
        return entityManager().createQuery("SELECT o FROM WeekAgentLog o", WeekAgentLog.class).getResultList();
    }
    
    public static WeekAgentLog WeekAgentLog.findWeekAgentLog(Long id) {
        if (id == null) return null;
        return entityManager().find(WeekAgentLog.class, id);
    }
    
    public static List<WeekAgentLog> WeekAgentLog.findWeekAgentLogEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM WeekAgentLog o", WeekAgentLog.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
