// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ks.code.calculator.domain;

import java.lang.Long;
import java.lang.String;
import java.util.Date;

privileged aspect WeekAgentLog_Roo_JavaBean {
    
    public Long WeekAgentLog.getCodeCreatorId() {
        return this.codeCreatorId;
    }
    
    public void WeekAgentLog.setCodeCreatorId(Long codeCreatorId) {
        this.codeCreatorId = codeCreatorId;
    }
    
    public String WeekAgentLog.getAgent() {
        return this.agent;
    }
    
    public void WeekAgentLog.setAgent(String agent) {
        this.agent = agent;
    }
    
    public Long WeekAgentLog.getCount() {
        return this.count;
    }
    
    public void WeekAgentLog.setCount(Long count) {
        this.count = count;
    }
    
    public String WeekAgentLog.getLogDay() {
        return this.logDay;
    }
    
    public void WeekAgentLog.setLogDay(String logDay) {
        this.logDay = logDay;
    }
    
    public Date WeekAgentLog.getWriteDate() {
        return this.writeDate;
    }
    
    public void WeekAgentLog.setWriteDate(Date writeDate) {
        this.writeDate = writeDate;
    }
    
}
