// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ks.code.calculator.domain;

import com.ks.code.calculator.domain.MonthAgentLog;
import java.lang.Integer;
import java.lang.Long;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.PersistenceContext;
import javax.persistence.Table;
import javax.persistence.Version;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MonthAgentLog_Roo_Entity {
    
    declare @type: MonthAgentLog: @Entity;
    
    declare @type: MonthAgentLog: @Table(name = "ks_month_agent_log");
    
    @PersistenceContext
    transient EntityManager MonthAgentLog.entityManager;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long MonthAgentLog.id;
    
    @Version
    @Column(name = "version")
    private Integer MonthAgentLog.version;
    
    public Long MonthAgentLog.getId() {
        return this.id;
    }
    
    public void MonthAgentLog.setId(Long id) {
        this.id = id;
    }
    
    public Integer MonthAgentLog.getVersion() {
        return this.version;
    }
    
    public void MonthAgentLog.setVersion(Integer version) {
        this.version = version;
    }
    
    @Transactional
    public void MonthAgentLog.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void MonthAgentLog.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            MonthAgentLog attached = MonthAgentLog.findMonthAgentLog(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void MonthAgentLog.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void MonthAgentLog.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public MonthAgentLog MonthAgentLog.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        MonthAgentLog merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
    public static final EntityManager MonthAgentLog.entityManager() {
        EntityManager em = new MonthAgentLog().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long MonthAgentLog.countMonthAgentLogs() {
        return entityManager().createQuery("SELECT COUNT(o) FROM MonthAgentLog o", Long.class).getSingleResult();
    }
    
    public static List<MonthAgentLog> MonthAgentLog.findAllMonthAgentLogs() {
        return entityManager().createQuery("SELECT o FROM MonthAgentLog o", MonthAgentLog.class).getResultList();
    }
    
    public static MonthAgentLog MonthAgentLog.findMonthAgentLog(Long id) {
        if (id == null) return null;
        return entityManager().find(MonthAgentLog.class, id);
    }
    
    public static List<MonthAgentLog> MonthAgentLog.findMonthAgentLogEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM MonthAgentLog o", MonthAgentLog.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
