// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ks.code.calculator.domain;

import java.lang.Long;
import java.lang.String;
import java.util.Date;

privileged aspect MonthAgentLog_Roo_JavaBean {
    
    public Long MonthAgentLog.getCodeCreatorId() {
        return this.codeCreatorId;
    }
    
    public void MonthAgentLog.setCodeCreatorId(Long codeCreatorId) {
        this.codeCreatorId = codeCreatorId;
    }
    
    public String MonthAgentLog.getAgent() {
        return this.agent;
    }
    
    public void MonthAgentLog.setAgent(String agent) {
        this.agent = agent;
    }
    
    public Long MonthAgentLog.getCount() {
        return this.count;
    }
    
    public void MonthAgentLog.setCount(Long count) {
        this.count = count;
    }
    
    public String MonthAgentLog.getLogDay() {
        return this.logDay;
    }
    
    public void MonthAgentLog.setLogDay(String logDay) {
        this.logDay = logDay;
    }
    
    public Date MonthAgentLog.getWriteDate() {
        return this.writeDate;
    }
    
    public void MonthAgentLog.setWriteDate(Date writeDate) {
        this.writeDate = writeDate;
    }
    
}
