// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ks.code.calculator.service;

import com.ks.code.calculator.domain.MonthAgentLog;
import java.lang.Long;
import java.lang.String;
import java.util.List;

privileged aspect MonthAgentLogServiceResult_Roo_JavaBean {
    
    public MonthAgentLog MonthAgentLogServiceResult.getMonthagentlog() {
        return this.monthagentlog;
    }
    
    public void MonthAgentLogServiceResult.setMonthagentlog(MonthAgentLog monthagentlog) {
        this.monthagentlog = monthagentlog;
    }
    
    public List<MonthAgentLog> MonthAgentLogServiceResult.getMonthagentlogList() {
        return this.monthagentlogList;
    }
    
    public void MonthAgentLogServiceResult.setMonthagentlogList(List<MonthAgentLog> monthagentlogList) {
        this.monthagentlogList = monthagentlogList;
    }
    
    public Long MonthAgentLogServiceResult.getCount() {
        return this.count;
    }
    
    public void MonthAgentLogServiceResult.setCount(Long count) {
        this.count = count;
    }
    
    public String MonthAgentLogServiceResult.getPageView() {
        return this.pageView;
    }
    
    public void MonthAgentLogServiceResult.setPageView(String pageView) {
        this.pageView = pageView;
    }
    
}
