// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ks.code.calculator.service;

import com.ks.code.calculator.domain.TimeAgentLog;
import java.lang.Long;
import java.lang.String;
import java.util.List;

privileged aspect TimeAgentLogServiceResult_Roo_JavaBean {
    
    public TimeAgentLog TimeAgentLogServiceResult.getTimeagentlog() {
        return this.timeagentlog;
    }
    
    public void TimeAgentLogServiceResult.setTimeagentlog(TimeAgentLog timeagentlog) {
        this.timeagentlog = timeagentlog;
    }
    
    public List<TimeAgentLog> TimeAgentLogServiceResult.getTimeagentlogList() {
        return this.timeagentlogList;
    }
    
    public void TimeAgentLogServiceResult.setTimeagentlogList(List<TimeAgentLog> timeagentlogList) {
        this.timeagentlogList = timeagentlogList;
    }
    
    public Long TimeAgentLogServiceResult.getCount() {
        return this.count;
    }
    
    public void TimeAgentLogServiceResult.setCount(Long count) {
        this.count = count;
    }
    
    public String TimeAgentLogServiceResult.getPageView() {
        return this.pageView;
    }
    
    public void TimeAgentLogServiceResult.setPageView(String pageView) {
        this.pageView = pageView;
    }
    
}
