// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ks.code.calculator.service;

import java.lang.String;

privileged aspect TimeAgentLogServiceResult_Roo_ToString {
    
    public String TimeAgentLogServiceResult.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Count: ").append(getCount()).append(", ");
        sb.append("PageView: ").append(getPageView()).append(", ");
        sb.append("Timeagentlog: ").append(getTimeagentlog()).append(", ");
        sb.append("TimeagentlogList: ").append(getTimeagentlogList() == null ? "null" : getTimeagentlogList().size());
        return sb.toString();
    }
    
}
