// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ks.code.calculator.service;

import java.lang.String;

privileged aspect WeekAgentLogServiceResult_Roo_ToString {
    
    public String WeekAgentLogServiceResult.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Count: ").append(getCount()).append(", ");
        sb.append("PageView: ").append(getPageView()).append(", ");
        sb.append("Weekagentlog: ").append(getWeekagentlog()).append(", ");
        sb.append("WeekagentlogList: ").append(getWeekagentlogList() == null ? "null" : getWeekagentlogList().size());
        return sb.toString();
    }
    
}
